### Topic 1: Variables & Dynamic Typing

#### Question 1.1

In [ ]:
age = 25
print(age)
print(type(age))

25
<class 'int'>

#### Question 1.2

In [ ]:
num = "10"
print(num, type(num))
num = 10
print(num, type(num))

10 <class 'str'>
10 <class 'int'>

#### Question 1.3

Python is dynamically typed, so a variable can refer to values of different types. In C or Java, int x declares x as an integer, so assigning 4.5 causes a type error or requires an explicit conversion.

#### Question 1.4

In [ ]:
x = 5
x = "five"
print(x)

five

### Topic 2: Common Data Types

#### Question 2.1

In [ ]:
a = 10
b = 3.14
c = "hello"
d = True
e = [1, 2, 3]

print(a, type(a))
print(b, type(b))
print(c, type(c))
print(d, type(d))
print(e, type(e))

10 <class 'int'>
3.14 <class 'float'>
hello <class 'str'>
True <class 'bool'>
[1, 2, 3] <class 'list'>

#### Question 2.2

A list can be changed after it is created, but a tuple cannot be changed.

```python
my_list = [1, 2, 3]
my_tuple = (1, 2, 3)
my_list[0] = 9
print(my_list)
# my_tuple[0] = 9 would cause an error.
```

#### Question 2.3

In [ ]:
price = 499.99
in_stock = True

if in_stock:
    print("Available")

Available

### Topic 3: Objects, Identity (is) vs Equality (==)

#### Question 3.1

`==` checks whether two values are equal. `is` checks whether two variables refer to the same object.

#### Question 3.2

In [ ]:
a = [1, 2, 3]
b = [1, 2, 3]
print(a == b)
print(a is b)

True
False

#### Question 3.3

In [ ]:
x = 100
y = 100
print(x is y)
print(x == y)

p = 1000
q = 1000
print(p is q)
print(p == q)

True
True
False
True

#### Question 3.4

In [ ]:
print(type(5))
print(type("hi"))
print(type([1, 2]))

<class 'int'>
<class 'str'>
<class 'list'>

### Topic 4: Strings & Methods

#### Question 4.1

In [ ]:
name = "pYTHOn"
print(name.upper())
print(name.lower())
print(name.title())

PYTHON
python
Python

#### Question 4.2

In [ ]:
s = "Hello"
s.lower()
print(s)

Hello

#### Question 4.3

In [ ]:
s = "Hello"
s = s.lower()
print(s)

hello

#### Question 4.4

In [ ]:
sentence = " Learning Python is fun "
clean_sentence = sentence.strip()
print(clean_sentence)
print(clean_sentence.count('n'))
print(clean_sentence.split())

Learning Python is fun
4
['Learning', 'Python', 'is', 'fun']

### Topic 5: Loops — for, range(), while

#### Question 5.1

In [ ]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10

#### Question 5.2

In [ ]:
for i in range(0, 31, 3):
    print(i)

0
3
6
9
12
15
18
21
24
27
30

#### Question 5.3

In [ ]:
for i in range(10, 0, -2):
    print(i)

10
8
6
4
2

#### Question 5.4

In [ ]:
i = 0
while i < 20:
    print(i)
    i += 4

0
4
8
12
16

#### Question 5.5

The condition i < 10 is checked 11 times: 10 times when it is True and once more when it becomes False.

### Topic 6: Conditions — if / elif / else, modulo (%)

#### Question 6.1

In [ ]:
for i in range(1, 21):
    if i % 2 == 0:
        print(i)

2
4
6
8
10
12
14
16
18
20

#### Question 6.2

In [ ]:
for i in range(1, 16):
    if i % 15 == 0:
        print("FizzBuzz")
    elif i % 3 == 0:
        print("Fizz")
    elif i % 5 == 0:
        print("Buzz")
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz

#### Question 6.3

In [ ]:
for i in range(0, 5):
    if i % 3 == 0:
        print(i)
    elif i % 3 == 1:
        print(i + 10)
    else:
        print(i - 10)

0
11
-8
3
14

#### Question 6.4

In [ ]:
number = int(input("Enter a number: "))
if number > 0:
    print("Positive")
elif number < 0:
    print("Negative")
else:
    print("Zero")

Enter a number: 5
Positive

### Topic 7: Functions & Passing Arguments

#### Question 7.1

In [ ]:
def my_abs(val):
    if val < 0:
        return 0 - val
    return val

print(my_abs(5))
print(my_abs(-5))
print(my_abs(0))

5
5
0

#### Question 7.2

my_abs("Hi") causes a TypeError because Python cannot compare a string with the integer 0 using <.

#### Question 7.3

In [ ]:
def print_abs(val):
    if val < 0:
        print(0 - val)
    else:
        print(val)

x = print_abs(-2.7)
print(x)

2.7
None

#### Question 7.4

In [ ]:
def inc_val(val):
    val = val + 1

x = 7
inc_val(x)
print(x)

7

#### Question 7.5

In [ ]:
def swap_message(val1, val2):
    val1, val2 = val2, val1
    print(val1, val2)

x = 6
y = 3
swap_message(x, y)
print(x, y)

3 6
6 3

### Topic 8: Scope — Local vs Global Variables

#### Question 8.1

In [ ]:
def my_abs(val):
    if val < 0:
        return 0 - val
    return val

print(my_abs(-5))
# print(val) would cause a NameError because val is local to the function.

5

#### Question 8.2

In [ ]:
counter = 0

def show_counter():
    print(counter)

show_counter()

0

#### Question 8.3

In [ ]:
counter = 0

def increment_counter():
    counter = counter + 1

# Calling increment_counter() raises UnboundLocalError because counter is treated as local.

#### Question 8.4

In [ ]:
counter = 0

def increment_counter():
    global counter
    counter = counter + 1

increment_counter()
print(counter)

1

### Scenario Based Questions

#### Question S1

In [ ]:
item_name = "Notebook"
print(item_name, type(item_name))
item_name = 101
print(item_name, type(item_name))

Notebook <class 'str'>
101 <class 'int'>

#### Question S2

In [ ]:
name = "Ananya"
roll_number = 21
height_in_cm = 152.5
is_hostel_student = True

print("Name:", name)
print("Roll Number:", roll_number)
print("Height:", height_in_cm)
print("Hostel Student:", is_hostel_student)

Name: Ananya
Roll Number: 21
Height: 152.5
Hostel Student: True

#### Question S3

In [ ]:
sam_age = 20
priya_age = 20
print(sam_age == priya_age)
print(sam_age is priya_age)

# == compares values and is checks object identity.

True
True

#### Question S4

In [ ]:
raw_name = " rohan MEHTA "
clean_name = raw_name.strip().title()
print(clean_name)

Rohan Mehta

#### Question S5

In [ ]:
for i in range(1, 8):
    print(f"Day {i}: Watered the plant")

Day 1: Watered the plant
Day 2: Watered the plant
Day 3: Watered the plant
Day 4: Watered the plant
Day 5: Watered the plant
Day 6: Watered the plant
Day 7: Watered the plant

#### Question S6

In [ ]:
i = 5
while i >= 1:
    print(i)
    i -= 1
print("Blast off!")

5
4
3
2
1
Blast off!

#### Question S7

In [ ]:
age = 10
if age < 12:
    print("Ticket price: ₹100")
else:
    print("Ticket price: ₹250")

age = 15
if age < 12:
    print("Ticket price: ₹100")
else:
    print("Ticket price: ₹250")

Ticket price: ₹100
Ticket price: ₹250

#### Question S8

In [ ]:
roll_number = 23
if roll_number % 2 == 0:
    print("Even roll number")
else:
    print("Odd roll number")

Odd roll number

#### Question S9

In [ ]:
def greet_student(name):
    print(f"Hello, {name}! Welcome to Python class.")

greet_student("Meera")
greet_student("Karan")

Hello, Meera! Welcome to Python class.
Hello, Karan! Welcome to Python class.

#### Question S10

In [ ]:
def add_numbers(a, b):
    return a + b

print(add_numbers(4, 7))

11

#### Question S11

In [ ]:
total_students = 0

def mark_present():
    global total_students
    total_students += 1

mark_present()
mark_present()
mark_present()
print(total_students)

3

In [ ]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

np.set_printoptions(suppress=True)
np.random.seed(42)

## Sheet 1 — NumPy Laboratory Practice

### Question 1

In [ ]:
nums = np.array([10, 20, 30, 40, 50])
print('Array:', nums)
print('Shape:', nums.shape)
print('Size:', nums.size)
print('Data type:', nums.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Size: 5
Data type: int64

### Question 2

In [ ]:
nums = np.arange(1, 13).reshape(3, 4)
print(nums)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

### Question 3

In [ ]:
print('Zeros:\n', np.zeros((2, 3)))
print('Ones:\n', np.ones((2, 3)))
print('Identity matrix:\n', np.eye(3))

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### Question 4

In [ ]:
print(np.arange(10, 51, 2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

### Question 5

In [ ]:
print(np.linspace(0, 1, 10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

### Question 6

In [ ]:
first_matrix = np.array([10, 20, 30])
second_matrix = np.array([2, 4, 5])
print('Addition:', first_matrix + second_matrix)
print('Subtraction:', first_matrix - second_matrix)
print('Multiplication:', first_matrix * second_matrix)
print('Division:', first_matrix / second_matrix)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]

### Question 7

In [ ]:
nums = np.array([2, 3, 4, 5])
print('Squares:', nums ** 2)
print('Cubes:', nums ** 3)

Squares: [ 4  9 16 25]
Cubes: [  8  27  64 125]

### Question 8

In [ ]:
nums = np.array([100, 200, 300])
increased = nums * 1.15
print(increased)

[115. 230. 345.]

### Question 9

In [ ]:
first_matrix = np.array([4, 8, 2, 9])
second_matrix = np.array([5, 3, 7, 6])
print('Maximum:', np.maximum(first_matrix, second_matrix))
print('Minimum:', np.minimum(first_matrix, second_matrix))

Maximum: [5 8 7 9]
Minimum: [4 3 2 6]

### Question 10

In [ ]:
nums = np.arange(21)
print('First five:', nums[:5])
print('Last five:', nums[-5:])
print('Index 5 to 15:', nums[5:16])
print('Every second element:', nums[::2])

First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second element: [ 0  2  4  6  8 10 12 14 16 18 20]

### Question 11

In [ ]:
nums = np.arange(10)
nums[:5] = 100
print(nums)

[100 100 100 100 100   5   6   7   8   9]

### Question 12

In [ ]:
base_array = np.array([1, 2, 3, 4, 5])
array_view = base_array[1:4]
separate_array = base_array[1:4].copy()
array_view[0] = 99
separate_array[1] = 88
print('Original changed by array_view:', base_array)
print('View:', array_view)
print('Copy (independent):', separate_array)

Original changed by array_view: [ 1 99  3  4  5]
View: [99  3  4]
Copy (independent): [ 2 88  4]

### Question 13

In [ ]:
nums = np.array([1, 2, 3, 4, 5])
print(nums[::-1])

[5 4 3 2 1]

### Question 14

In [ ]:
matrix = np.array([[10,20,30], [40,50,60], [70,80,90]])
print('Second row:', matrix[1, :])
print('Third column:', matrix[:, 2])
print('Element 50:', matrix[1, 1])

Second row: [40 50 60]
Third column: [30 60 90]
Element 50: 50

### Question 15

In [ ]:
matrix = np.array([[10,20,30], [40,50,60], [70,80,90]])
print(matrix[:2, 1:3])

[[20 30]
 [50 60]]

### Question 16

In [ ]:
matrix = np.arange(1, 26).reshape(5, 5)
print('Matrix:\n', matrix)
print('First row:', matrix[0, :])
print('Last column:', matrix[:, -1])
print('Middle element:', matrix[2, 2])
print('Top-left 3x3:\n', matrix[:3, :3])

Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Middle element: 13
Top-left 3x3:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]

### Question 17

In [ ]:
print(np.arange(1, 13).reshape(3, 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

### Question 18

In [ ]:
nums = np.arange(1, 11)
print(nums.reshape(2, 5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

### Question 19

In [ ]:
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

### Question 20

In [ ]:
nums = np.arange(24).reshape(2, 3, 4)
print('Original shape:', nums.shape)
print('Transpose shape:', nums.transpose(1, 0, 2).shape)
print('Swap axes shape:', np.swapaxes(nums, 0, 2).shape)

Original shape: (2, 3, 4)
Transpose shape: (3, 2, 4)
Swap axes shape: (4, 3, 2)

### Question 21

In [ ]:
first_matrix = np.arange(1, 10).reshape(3, 3)
second_matrix = np.arange(9, 0, -1).reshape(3, 3)
print('Addition:\n', first_matrix + second_matrix)
print('Element-wise multiplication:\n', first_matrix * second_matrix)

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

### Question 22

In [ ]:
first_matrix = np.array([[1, 2], [3, 4]])
second_matrix = np.array([[5, 6], [7, 8]])
print(np.dot(first_matrix, second_matrix))

[[19 22]
 [43 50]]

### Question 23

In [ ]:
first_matrix = np.array([[1, 2], [3, 4], [5, 6]])
print('Transpose:\n', first_matrix.T)
print('A.T dot A:\n', np.dot(first_matrix.T, first_matrix))

Transpose:
 [[1 3 5]
 [2 4 6]]
A.T dot A:
 [[35 44]
 [44 56]]

### Question 24

In [ ]:
nums = np.array([1, 4, 9, 16, 25])
print(np.sqrt(nums))

[1. 2. 3. 4. 5.]

### Question 25

In [ ]:
nums = np.array([0, 1, 2])
print(np.exp(nums))

[1.         2.71828183 7.3890561 ]

### Question 26

In [ ]:
nums = np.random.randn(5)
print('Array:', nums)
print('Square root (of non-negative values only):', np.sqrt(np.clip(nums, 0, None)))
print('Exponential:', np.exp(nums))
print('Absolute values:', np.abs(nums))

Array: [ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
Square root (of non-negative values only): [0.70477951 0.         0.80479099 1.23411096 0.        ]
Exponential: [1.64331272 0.87086849 1.91111824 4.58609939 0.79124045]
Absolute values: [0.49671415 0.1382643  0.64768854 1.52302986 0.23415337]

### Question 27

In [ ]:
first_matrix = np.random.rand(5)
second_matrix = np.random.rand(5)
print('first_matrix:', first_matrix)
print('second_matrix:', second_matrix)
print('Maximum:', np.maximum(first_matrix, second_matrix))

first_matrix: [0.05808361 0.86617615 0.60111501 0.70807258 0.02058449]
second_matrix: [0.96990985 0.83244264 0.21233911 0.18182497 0.18340451]
Maximum: [0.96990985 0.86617615 0.60111501 0.70807258 0.18340451]

### Question 28

In [ ]:
score_data = np.array([35, 72, 48, 90, 55, 28])
print(np.where(score_data < 40, 0, score_data))

[ 0 72 48 90 55  0]

### Question 29

In [ ]:
income_data = np.array([32000, 50000, 72000, 48000, 95000])
print(np.where(income_data >= 50000, 'High', 'Low'))

['Low' 'High' 'High' 'Low' 'High']

### Question 30

In [ ]:
nums = np.array([10, 35, 22, 48, 30, 31])
print(np.where(nums > 30, 100, nums))

[ 10 100  22 100  30 100]

### Question 31

In [ ]:
matrix = np.arange(1, 10).reshape(3, 3)
print('Sum:', np.sum(matrix))
print('Mean:', np.mean(matrix))
print('Variance:', np.var(matrix))
print('Standard deviation:', np.std(matrix))

Sum: 45
Mean: 5.0
Variance: 6.666666666666667
Standard deviation: 2.581988897471611

### Question 32

In [ ]:
matrix = np.arange(1, 10).reshape(3, 3)
print('Row-wise sums:', np.sum(matrix, axis=1))
print('Column-wise sums:', np.sum(matrix, axis=0))

Row-wise sums: [ 6 15 24]
Column-wise sums: [12 15 18]

### Question 33

In [ ]:
score_data = np.array([76, 82, 69, 91, 58, 88, 73, 95, 64, 80])
print('Mean:', np.mean(score_data))
print('Standard deviation:', np.std(score_data))
print('Minimum:', np.min(score_data))
print('Maximum:', np.max(score_data))

Mean: 77.6
Standard deviation: 11.324310133513652
Minimum: 58
Maximum: 95

### Question 34

In [ ]:
values = np.array([True, True, False])
print('any:', np.any(values))
print('all:', np.all(values))

any: True
all: False

### Question 35

In [ ]:
nums = np.random.rand(10)
print('Original:', nums)
print('Sorted:', np.sort(nums))

Original: [0.30424224 0.52475643 0.43194502 0.29122914 0.61185289 0.13949386
 0.29214465 0.36636184 0.45606998 0.78517596]
Sorted: [0.13949386 0.29122914 0.29214465 0.30424224 0.36636184 0.43194502
 0.45606998 0.52475643 0.61185289 0.78517596]

### Question 36

In [ ]:
nums = np.array([2, 3, 2, 5, 3, 7, 5])
print(np.unique(nums))

[2 3 5 7]

### Question 37

In [ ]:
score_data = np.array([70, 85, 70, 92, 85, 68, 92])
print(np.unique(score_data))

[68 70 85 92]

### Question 38

In [ ]:
nums = np.array([10, 20, 30, 40])
chosen_values = np.array([20, 50, 40])
print(np.in1d(chosen_values, nums))

[ True False  True]

/tmp/ipykernel_541/2695934556.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(chosen_values, nums))

### Question 39

In [ ]:
score_data = np.array([[65, 70, 80], [40, 45, 50], [90, 85, 88], [55, 60, 58], [30, 35, 40], [72, 68, 75], [49, 51, 50], [80, 82, 79], [44, 46, 48], [60, 62, 64]])
student_total = score_data.sum(axis=1)
student_avg = score_data.mean(axis=1)
print('Totals:', student_total)
print('Averages:', student_avg)
print('Students with average >= 50 (1-based):', np.where(student_avg >= 50)[0] + 1)

Totals: [215 135 263 173 105 215 150 241 138 186]
Averages: [71.66666667 45.         87.66666667 57.66666667 35.         71.66666667
 50.         80.33333333 46.         62.        ]
Students with average >= 50 (1-based): [ 1  3  4  6  7  8 10]

### Question 40

In [ ]:
matrix = np.arange(1, 17).reshape(4, 4)
print('Matrix:\n', matrix)
print('Transpose:\n', matrix.T)
print('Row sums:', matrix.sum(axis=1))
print('Column sums:', matrix.sum(axis=0))
print('Mean:', matrix.mean())
print('Maximum:', matrix.max())
print('Minimum:', matrix.min())
print('Central 2x2:\n', matrix[1:3, 1:3])

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row sums: [10 26 42 58]
Column sums: [28 32 36 40]
Mean: 8.5
Maximum: 16
Minimum: 1
Central 2x2:
 [[ 6  7]
 [10 11]]

### Question 41

In [ ]:
obs = np.random.randn(20)
print('Observations:', obs)
print('Mean:', obs.mean())
print('Standard deviation:', obs.std())
print('Minimum:', obs.min())
print('Maximum:', obs.max())
print('Sorted:', np.sort(obs))
print('Negative values replaced with zero:', np.where(obs < 0, 0, obs))

Observations: [-0.23413696  0.0675282  -1.42474819 -0.54438272  0.11092259 -1.15099358
  0.37569802 -0.60063869 -0.29169375 -0.60170661  1.85227818 -0.01349722
 -1.05771093  0.82254491 -1.22084365  0.2088636  -1.95967012 -1.32818605
  0.19686124  0.73846658]
Mean: -0.3027522576634893
Standard deviation: 0.8884708298751535
Minimum: -1.9596701238797756
Maximum: 1.8522781845089378
Sorted: [-1.95967012 -1.42474819 -1.32818605 -1.22084365 -1.15099358 -1.05771093
 -0.60170661 -0.60063869 -0.54438272 -0.29169375 -0.23413696 -0.01349722
  0.0675282   0.11092259  0.19686124  0.2088636   0.37569802  0.73846658
  0.82254491  1.85227818]
Negative values replaced with zero: [0.         0.0675282  0.         0.         0.11092259 0.
 0.37569802 0.         0.         0.         1.85227818 0.
 0.         0.82254491 0.         0.2088636  0.         0.
 0.19686124 0.73846658]

### Question 42

In [ ]:
first_matrix = np.arange(1, 10).reshape(3, 3)
second_matrix = np.arange(9, 0, -1).reshape(3, 3)
print('A + B:\n', first_matrix + second_matrix)
print('A * B element-wise:\n', first_matrix * second_matrix)
matrix_product = first_matrix @ second_matrix
print('Matrix matrix_product:\n', matrix_product)
print('Transpose of A:\n', first_matrix.T)
print('Maximum in matrix matrix_product:', matrix_product.max())
print('Minimum in matrix matrix_product:', matrix_product.min())

A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
A * B element-wise:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix matrix_product:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Maximum in matrix matrix_product: 138
Minimum in matrix matrix_product: 18

### Question 43

In [ ]:
nums = np.arange(1, 25)
matrix = nums.reshape(4, 6)
print('Matrix:\n', matrix)
print('Rows 2 and 4:\n', matrix[[1, 3], :])
print('Columns 2 and 5:\n', matrix[:, [1, 4]])
print('Transpose:\n', matrix.T)
print('Row means:', matrix.mean(axis=1))
print('Column sums:', matrix.sum(axis=0))
print('Unique values:', np.unique(matrix))

Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Rows 2 and 4:
 [[ 7  8  9 10 11 12]
 [19 20 21 22 23 24]]
Columns 2 and 5:
 [[ 2  5]
 [ 8 11]
 [14 17]
 [20 23]]
Transpose:
 [[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]
Row means: [ 3.5  9.5 15.5 21.5]
Column sums: [40 44 48 52 56 60]
Unique values: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

## Sheet 2 — Pandas Series Practice

### Question 1

In [ ]:
sales_data = Series([120, 150, 180, 210], name='sales_data')
print(sales_data)

0    120
1    150
2    180
3    210
Name: sales_data, dtype: int64

### Question 2

In [ ]:
score_data = Series([72, 81, 69, 90])
print(score_data.values)

[72 81 69 90]

### Question 3

In [ ]:
print(score_data.index)

RangeIndex(start=0, stop=4, step=1)

### Question 4

In [ ]:
weekly_temp = Series([28, 31, 30, 29], index=['Mon', 'Tue', 'Wed', 'Thu'])
print(weekly_temp)

Mon    28
Tue    31
Wed    30
Thu    29
dtype: int64

### Question 5

In [ ]:
city_population = Series([35, 42, 31], index=['Delhi', 'Mumbai', 'Jaipur'])
print(city_population['Jaipur'])

31

### Question 6

In [ ]:
score_values = Series([35, 68, 44, 79, 52])
print(score_values[score_values > 50])

1    68
3    79
4    52
dtype: int64

### Question 7

In [ ]:
subject_scores = Series([76, 83, 91], index=['Physics', 'Chemistry', 'Maths'])
print('Chemistry' in subject_scores.index)

True

### Question 8

In [ ]:
series_data = Series([10, 20], index=['A', 'B'])
result_dict = series_data.to_dict()
print(result_dict)

{'A': 10, 'B': 20}

### Question 9

In [ ]:
prices = {'Pen': 10, 'Notebook': 55, 'Bag': 700}
item_prices = Series(prices, name='item_prices')
print(item_prices)

Pen          10
Notebook     55
Bag         700
Name: item_prices, dtype: int64

### Question 10

In [ ]:
prices = {'Pen': 10, 'Notebook': 55, 'Bag': 700}
series_data = Series(prices)
print(series_data.index)

Index(['Pen', 'Notebook', 'Bag'], dtype='object')

### Question 11

In [ ]:
records = {'A': 10, 'B': 20, 'C': 30}
series_data = Series(records, index=['A', 'B', 'C', 'D'])
print(series_data)

A    10.0
B    20.0
C    30.0
D     NaN
dtype: float64

### Question 12

In [ ]:
print(pd.isnull(series_data))

A    False
B    False
C    False
D     True
dtype: bool

### Question 13

In [ ]:
print(pd.notnull(series_data))

A     True
B     True
C     True
D    False
dtype: bool

### Question 14

In [ ]:
sales_data = Series([120, 150, 180, 210])
sales_data.name = 'Monthly Sales'
print(sales_data.name)

Monthly Sales

### Question 15

In [ ]:
sales_data.index.name = 'Month'
print(sales_data)

Month
0    120
1    150
2    180
3    210
Name: Monthly Sales, dtype: int64

### Question 16

In [ ]:
series_data = Series([18, 45, 27, 61], index=['P', 'Q', 'R', 'S'])
print(series_data[series_data > 30])

Q    45
S    61
dtype: int64

### Question 17

In [ ]:
series_data = Series([500, 600, 700], index=['East', 'West', 'North'])
print('West' in series_data)
print(500 in series_data)

True
False

### Question 18

In [ ]:
city_data = {'Delhi': 80, 'Pune': 65, 'Kochi': 70}
series_data = Series(city_data, index=['Delhi', 'Kochi', 'Pune', 'Chennai'])
print(series_data)

Delhi      80.0
Kochi      70.0
Pune       65.0
Chennai     NaN
dtype: float64

### Question 19

In [ ]:
series_data = Series({'W': 5, 'X': 10, 'Y': 15}, index=['W', 'X', 'Y', 'Z'])
print(pd.isnull(series_data))

W    False
X    False
Y    False
Z     True
dtype: bool

### Question 20

In [ ]:
print(pd.notnull(series_data))

W     True
X     True
Y     True
Z    False
dtype: bool

### Question 21

In [ ]:
first_series = Series([10, 20, 30], index=['A', 'B', 'C'])
second_series = Series([1, 2, 3], index=['C', 'A', 'B'])
print(first_series + second_series)

A    12
B    23
C    31
dtype: int64

### Question 22

In [ ]:
first_series = Series({'A': 12, 'B': 18})
second_series = Series({'B': 5, 'C': 9})
print(first_series + second_series)

A     NaN
B    23.0
C     NaN
dtype: float64

### Question 23

In [ ]:
stock_data = Series([25, 40, 18], index=['Item1', 'Item2', 'Item3'])
stock_map = stock_data.to_dict()
stock_again = Series(stock_map)
print(stock_map)
print(stock_again)

{'Item1': 25, 'Item2': 40, 'Item3': 18}
Item1    25
Item2    40
Item3    18
dtype: int64

### Question 24

In [ ]:
subject_data = {'Maths': 88, 'Science': 74, 'English': 69, 'History': 81}
subject_marks = Series(subject_data, index=['History', 'English', 'Science', 'Maths'])
print(subject_marks[subject_marks > 70])

History    81
Science    74
Maths      88
dtype: int64

### Question 25

In [ ]:
revenue_series = Series([2500, 3200, 2800], index=['Agra', 'Delhi', 'Jaipur'])

revenue_series.name = 'Revenue'
revenue_series.index.name = 'Branch'

print(revenue_series)

Branch
Agra      2500
Delhi     3200
Jaipur    2800
Name: Revenue, dtype: int64

### Question 26

In [ ]:
north_data = Series({'Jan': 40, 'Feb': 55, 'Mar': 60})
south_data = Series({'Feb': 20, 'Mar': 25, 'Apr': 30})
combined = north_data + south_data
print(combined)

Apr     NaN
Feb    75.0
Jan     NaN
Mar    85.0
dtype: float64

### Question 27

In [ ]:
data_map = {'Red': 12, 'Blue': 18, 'Green': 24}
label_order = ['Green', 'Red', 'Yellow', 'Blue']
series_result = Series(data_map, index=label_order)
print(series_result)
print(pd.isnull(series_result))

Green     24.0
Red       12.0
Yellow     NaN
Blue      18.0
dtype: float64
Green     False
Red       False
Yellow     True
Blue      False
dtype: bool

### Question 28

In [ ]:
series_data = Series([90, 75, 82], index=['Ravi', 'Aman', 'Neha'])
data_map = series_data.to_dict()
second_series = Series(data_map)
print('Dictionary:', data_map)
print(second_series)
print('Same labelled records:', series_data.equals(second_series))

Dictionary: {'Ravi': 90, 'Aman': 75, 'Neha': 82}
Ravi    90
Aman    75
Neha    82
dtype: int64
Same labelled records: True

### Question 29

In [ ]:
sales_data = Series([650, 420, 800, 510], index=['Pen', 'Book', 'Bag', 'Bottle'], name='Sales')
print('Values:', sales_data.values)
print('Index:', sales_data.index)
print('Bag sales_data:', sales_data['Bag'])
print('Sales above 500:\n', sales_data[sales_data > 500])
print('Book exists:', 'Book' in sales_data.index)
print('Dictionary:', sales_data.to_dict())

Values: [650 420 800 510]
Index: Index(['Pen', 'Book', 'Bag', 'Bottle'], dtype='object')
Bag sales_data: 800
Sales above 500:
 Pen       650
Bag       800
Bottle    510
Name: Sales, dtype: int64
Book exists: True
Dictionary: {'Pen': 650, 'Book': 420, 'Bag': 800, 'Bottle': 510}

### Question 30

In [ ]:
records = {'A': 15, 'B': 35, 'C': 25}
series_data = Series(records, index=['C', 'A', 'D', 'B'])
series_data.name = 'Observations'
series_data.index.name = 'Category'
print(series_data)
print(series_data[series_data > 20])
print(pd.notnull(series_data))
print('Series name:', series_data.name)
print('Index name:', series_data.index.name)

Category
C    25.0
A    15.0
D     NaN
B    35.0
Name: Observations, dtype: float64
Category
C    25.0
B    35.0
Name: Observations, dtype: float64
Category
C     True
A     True
D    False
B     True
Name: Observations, dtype: bool
Series name: Observations
Index name: Category

## Sheet 3 — Pandas DataFrames Lab Practice

### Question 1

In [ ]:
class_df = DataFrame({'Name': ['Aarav', 'Diya', 'Kabir', 'Meera'], 'Age': [18, 19, 18, 20], 'City': ['Agra', 'Delhi', 'Jaipur', 'Pune']})
class_df

    Name  Age    City
0  Aarav   18    Agra
1   Diya   19   Delhi
2  Kabir   18  Jaipur
3  Meera   20    Pune

### Question 2

In [ ]:
display(class_df)

    Name  Age    City
0  Aarav   18    Agra
1   Diya   19   Delhi
2  Kabir   18  Jaipur
3  Meera   20    Pune

### Question 3

In [ ]:
print(class_df.columns)

Index(['Name', 'Age', 'City'], dtype='object')

### Question 4

In [ ]:
print(class_df['Name'])

0    Aarav
1     Diya
2    Kabir
3    Meera
Name: Name, dtype: object

### Question 5

In [ ]:
print(class_df['City'])

0      Agra
1     Delhi
2    Jaipur
3      Pune
Name: City, dtype: object

### Question 6

In [ ]:
student_city_view = class_df[['Name', 'City']]
display(student_city_view)

    Name    City
0  Aarav    Agra
1   Diya   Delhi
2  Kabir  Jaipur
3  Meera    Pune

### Question 7

In [ ]:
library_df = DataFrame({'Book': ['Python Basics', 'Data Science', 'Java Guide'], 'Author': ['A. Shah', 'R. Kumar', 'S. Mehta'], 'Price': [350, 520, 400]})
display(library_df)

            Book    Author  Price
0  Python Basics   A. Shah    350
1   Data Science  R. Kumar    520
2     Java Guide  S. Mehta    400

### Question 8

In [ ]:
library_df['Publisher'] = 'ABC Publications'
display(library_df)

            Book    Author  Price         Publisher
0  Python Basics   A. Shah    350  ABC Publications
1   Data Science  R. Kumar    520  ABC Publications
2     Java Guide  S. Mehta    400  ABC Publications

### Question 9

In [ ]:
item_df = DataFrame({'Item': ['A', 'B', 'C', 'D', 'E']})
item_df['SerialNo'] = np.arange(5)
display(item_df)

  Item  SerialNo
0    A         0
1    B         1
2    C         2
3    D         3
4    E         4

### Question 10

In [ ]:
del item_df['SerialNo']
display(item_df)

  Item
0    A
1    B
2    C
3    D
4    E

### Question 11

In [ ]:
film_df = DataFrame({'Movie': ['Film A', 'Film B', 'Film C'], 'Year': [2021, 2023, 2024], 'Rating': [7.8, 8.2, 7.5]})
display(film_df)

    Movie  Year  Rating
0  Film A  2021     7.8
1  Film B  2023     8.2
2  Film C  2024     7.5

### Question 12

In [ ]:
film_view = DataFrame(film_df, columns=['Movie', 'Rating', 'Director'])
display(film_view)

    Movie  Rating  Director
0  Film A     7.8       NaN
1  Film B     8.2       NaN
2  Film C     7.5       NaN

### Question 13

In [ ]:
city_branch = Series(['Agra', 'Delhi'], index=[0, 3])
print(city_branch)

0     Agra
3    Delhi
dtype: object

### Question 14

In [ ]:
branch_df = DataFrame({'Student': ['A', 'B', 'C', 'D']})
branch_df['Branch'] = city_branch
display(branch_df)

  Student Branch
0       A   Agra
1       B    NaN
2       C    NaN
3       D  Delhi

### Question 15

In [ ]:
copied_df = pd.DataFrame({
    'Name': ['Aman', 'Sara', 'Rohan'],
    'Age': [19, 20, 18],
    'City': ['Agra', 'Delhi', 'Jaipur']
})

display(copied_df)

    Name  Age    City
0   Aman   19    Agra
1   Sara   20   Delhi
2  Rohan   18  Jaipur

### Question 16

In [ ]:
staff_df = DataFrame({'Employee': ['Asha', 'Rohan', 'Ishita', 'Dev', 'Maya'], 'Department': ['IT', 'HR', 'Sales', 'IT', 'Finance'], 'Experience': [2, 5, 3, 1, 7]})
display(staff_df[['Employee', 'Experience']])

  Employee  Experience
0     Asha           2
1    Rohan           5
2   Ishita           3
3      Dev           1
4     Maya           7

### Question 17

In [ ]:
print(staff_df['Department'])
print(staff_df.columns)

0         IT
1         HR
2      Sales
3         IT
4    Finance
Name: Department, dtype: object
Index(['Employee', 'Department', 'Experience'], dtype='object')

### Question 18

In [ ]:
staff_df['Office'] = 'Head Office'
display(staff_df)

  Employee Department  Experience       Office
0     Asha         IT           2  Head Office
1    Rohan         HR           5  Head Office
2   Ishita      Sales           3  Head Office
3      Dev         IT           1  Head Office
4     Maya    Finance           7  Head Office

### Question 19

In [ ]:
staff_df['Office'] = np.arange(5)
display(staff_df)

  Employee Department  Experience  Office
0     Asha         IT           2       0
1    Rohan         HR           5       1
2   Ishita      Sales           3       2
3      Dev         IT           1       3
4     Maya    Finance           7       4

### Question 20

In [ ]:
office_places = Series(['Delhi', 'Mumbai', 'Pune'], index=[0, 2, 4])
staff_df['Office'] = office_places
display(staff_df)

  Employee Department  Experience  Office
0     Asha         IT           2   Delhi
1    Rohan         HR           5     NaN
2   Ishita      Sales           3  Mumbai
3      Dev         IT           1     NaN
4     Maya    Finance           7    Pune

### Question 21

In [ ]:
del staff_df['Office']
display(staff_df)

  Employee Department  Experience
0     Asha         IT           2
1    Rohan         HR           5
2   Ishita      Sales           3
3      Dev         IT           1
4     Maya    Finance           7

### Question 22

In [ ]:
goods_df = DataFrame({'Product': ['Pen', 'Bag', 'Bottle'], 'Category': ['Stationery', 'Accessories', 'Utility'], 'Price': [10, 700, 120]})
product_view = goods_df[['Price', 'Product', 'Category']]
display(product_view)

   Price Product     Category
0     10     Pen   Stationery
1    700     Bag  Accessories
2    120  Bottle      Utility

### Question 23

In [ ]:
source = {'Name': ['Aman', 'Sara'], 'Age': [19, 20], 'City': ['Agra', 'Delhi']}
chosen_columns_df = DataFrame(source, columns=['Name', 'Age', 'City', 'Grade'])
display(chosen_columns_df)

   Name  Age   City Grade
0  Aman   19   Agra   NaN
1  Sara   20  Delhi   NaN

### Question 24

In [ ]:
marks_df = DataFrame({'Name': ['A', 'B', 'C'], 'Total Marks': [78, 91, 85]})
print(marks_df['Total Marks'])

0    78
1    91
2    85
Name: Total Marks, dtype: int64

### Question 25

In [ ]:
copied_df = pd.DataFrame({
    'Name': ['Aman', 'Sara', 'Rohan'],
    'Age': [19, 20, 18],
    'City': ['Agra', 'Delhi', 'Jaipur'],
    'Total Marks': [82, 91, 75]
})

print(copied_df.columns)

sample_columns = copied_df.iloc[:, :3]

display(sample_columns)

Index(['Name', 'Age', 'City', 'Total Marks'], dtype='object')

    Name  Age    City
0   Aman   19    Agra
1   Sara   20   Delhi
2  Rohan   18  Jaipur

### Question 26

In [ ]:
course_data = DataFrame({'Student': ['A', 'B', 'C', 'D', 'E'], 'Course': ['Python', 'Java', 'SQL', 'Python', 'Java'], 'Score': [88, 76, 91, 69, 84]})
print(course_data.columns)
print(course_data['Student'])
display(course_data[['Student', 'Score']])
course_data['Batch'] = '2026'
display(course_data)

Index(['Student', 'Course', 'Score'], dtype='object')
0    A
1    B
2    C
3    D
4    E
Name: Student, dtype: object

  Student  Score
0       A     88
1       B     76
2       C     91
3       D     69
4       E     84

  Student  Course  Score Batch
0       A  Python     88  2026
1       B    Java     76  2026
2       C     SQL     91  2026
3       D  Python     69  2026
4       E    Java     84  2026

### Question 27

In [ ]:
trip_df = DataFrame({'Destination': ['Agra', 'Delhi', 'Jaipur', 'Pune', 'Goa']})
trip_df['Code'] = np.arange(5)
print('After np.arange:')
display(trip_df)
trip_codes = Series([101, 104], index=[1, 4])
trip_df['Code'] = trip_codes
print('After Series assignment:')
display(trip_df)

After np.arange:

  Destination  Code
0        Agra     0
1       Delhi     1
2      Jaipur     2
3        Pune     3
4         Goa     4

After Series assignment:

  Destination   Code
0        Agra    NaN
1       Delhi  101.0
2      Jaipur    NaN
3        Pune    NaN
4         Goa  104.0

### Question 28

In [ ]:
school_df = DataFrame({'Student': ['A', 'B', 'C'], 'Class': [9, 10, 9], 'Section': ['A', 'B', 'A']})
school_view = DataFrame(school_df, columns=['Student', 'Class', 'Section', 'House'])
display(school_view)
school_view['House'] = 'Blue House'
display(school_view)

  Student  Class Section  House
0       A      9       A    NaN
1       B     10       B    NaN
2       C      9       A    NaN

  Student  Class Section       House
0       A      9       A  Blue House
1       B     10       B  Blue House
2       C      9       A  Blue House

### Question 29

In [ ]:
store_df = DataFrame({'Item': ['Pen', 'Book', 'Bag', 'Bottle'], 'Quantity': [20, 12, 5, 8]})
store_df['Shelf'] = Series(['Top', 'Bottom'], index=[0, 2])
print('After adding Shelf:')
display(store_df)
del store_df['Shelf']
print('After deleting Shelf:')
display(store_df)

After adding Shelf:

     Item  Quantity   Shelf
0     Pen        20     Top
1    Book        12     NaN
2     Bag         5  Bottom
3  Bottle         8     NaN

After deleting Shelf:

     Item  Quantity
0     Pen        20
1    Book        12
2     Bag         5
3  Bottle         8

### Question 30

In [ ]:
lab_df = pd.DataFrame({
    'Name': ['Aman', 'Sara', 'Rohan'],
    'Total Marks': [82, 91, 75],
    'City': ['Agra', 'Delhi', 'Jaipur'],
    'Age': [19, 20, 18]
})

display(lab_df)

print(lab_df.columns)

print(lab_df['Name'])

print(lab_df['Total Marks'])

selected_df = lab_df[['Name', 'Total Marks', 'City']]
display(selected_df)

lab_df['Reviewed'] = 'Yes'
display(lab_df)

del lab_df['Reviewed']
display(lab_df)

    Name  Total Marks    City  Age
0   Aman           82    Agra   19
1   Sara           91   Delhi   20
2  Rohan           75  Jaipur   18

Index(['Name', 'Total Marks', 'City', 'Age'], dtype='object')
0     Aman
1     Sara
2    Rohan
Name: Name, dtype: object
0    82
1    91
2    75
Name: Total Marks, dtype: int64

    Name  Total Marks    City
0   Aman           82    Agra
1   Sara           91   Delhi
2  Rohan           75  Jaipur

    Name  Total Marks    City  Age Reviewed
0   Aman           82    Agra   19      Yes
1   Sara           91   Delhi   20      Yes
2  Rohan           75  Jaipur   18      Yes

    Name  Total Marks    City  Age
0   Aman           82    Agra   19
1   Sara           91   Delhi   20
2  Rohan           75  Jaipur   18